services:
  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/app

  mysql:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=csy2088
      - MYSQL_DATABASE=csy2088
      - MYSQL_USER=csy2088
      - MYSQL_PASSWORD=csy2088
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: